version: '3'
services:
  app-tickets:
    build: ./tickets
    # volumes:
    #   - .:/usr/src
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
  app-router:
    build: ./router
    # command: rails s -b 0.0.0.0
    # volumes:
    #   - .:/usr/src
    depends_on:
      - app-tickets
    ports:
      - 3000:3000
volumes:
  postgres:
