version: '3'
services:
  tickets:
    build: ./tickets
    #volumes:
    #  - .:/usr/src
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  transaction:
    build: ./transactions
    #volumes:
     # - .:/usr/src
    ports:
      - 3001:3000
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
  redis:
    image: redis:alpine
    volumes:
      - redis:/data
volumes:
  redis:
  postgres:
