version: '3'
services:
  transaction:
    build: .
    volumes:
      - .:/usr/src
    ports:
      - 3001:3000
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
  redis:
    image: redis:alpine
    volumes:
      - redis:/data
volumes:
  redis:



